# Classification Case Study

### Import libraries 

In [1]:
# Importing required packages
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
sns.set(style='white')

## Load data from final csv

In [2]:
train = pd.read_csv("final_train.csv")

In [3]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 564 entries, 0 to 563
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Gender          564 non-null    object 
 1   Married         564 non-null    object 
 2   Dependents      564 non-null    int64  
 3   Education       564 non-null    object 
 4   SelfEmployed    564 non-null    object 
 5   LoanAmountTerm  564 non-null    float64
 6   CreditHistory   564 non-null    float64
 7   PropertyArea    564 non-null    object 
 8   LoanStatus      564 non-null    int64  
 9   LoanAmountLog   564 non-null    float64
 10  IncomeLog       564 non-null    float64
dtypes: float64(4), int64(2), object(5)
memory usage: 48.6+ KB


In [4]:
X = train.drop(columns=['LoanStatus'])
y = train.LoanStatus

In [5]:
X = pd.get_dummies(X)  # One Hot Encoding 

In [6]:
X.columns

Index(['Dependents', 'LoanAmountTerm', 'CreditHistory', 'LoanAmountLog',
       'IncomeLog', 'Gender_Female', 'Gender_Male', 'Married_No',
       'Married_Yes', 'Education_Graduate', 'Education_Not Graduate',
       'SelfEmployed_No', 'SelfEmployed_Yes', 'PropertyArea_Rural',
       'PropertyArea_Semiurban', 'PropertyArea_Urban'],
      dtype='object')

In [7]:
X.sample(5)

Dependents  LoanAmountTerm  CreditHistory  LoanAmountLog  IncomeLog  \
127           2           360.0            1.0       4.859812   8.635865   
382           0           360.0            1.0       4.094345   8.004700   
271           0           480.0            0.0       4.962845   8.597297   
6             0           360.0            1.0       4.553877   8.255569   
451           0           360.0            1.0       4.317488   7.797702   

     Gender_Female  Gender_Male  Married_No  Married_Yes  Education_Graduate  \
127              0            1           0            1                   0   
382              1            0           1            0                   1   
271              1            0           1            0                   1   
6                0            1           0            1                   0   
451              0            1           1            0                   1   

     Education_Not Graduate  SelfEmployed_No  SelfEmployed_Yes  \
127                       1                1                 0   
382                       0                1                 0   
271                       0                1                 0   
6                         1                1                 0   
451                       0                1                 0   

     PropertyArea_Rural  PropertyArea_Semiurban  PropertyArea_Urban  
127                   1                       0                   0  
382                   0                       0                   1  
271                   0                       0                   1  
6                     0                       0                   1  
451                   0                       0                   1

In [8]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 564 entries, 0 to 563
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Dependents              564 non-null    int64  
 1   LoanAmountTerm          564 non-null    float64
 2   CreditHistory           564 non-null    float64
 3   LoanAmountLog           564 non-null    float64
 4   IncomeLog               564 non-null    float64
 5   Gender_Female           564 non-null    uint8  
 6   Gender_Male             564 non-null    uint8  
 7   Married_No              564 non-null    uint8  
 8   Married_Yes             564 non-null    uint8  
 9   Education_Graduate      564 non-null    uint8  
 10  Education_Not Graduate  564 non-null    uint8  
 11  SelfEmployed_No         564 non-null    uint8  
 12  SelfEmployed_Yes        564 non-null    uint8  
 13  PropertyArea_Rural      564 non-null    uint8  
 14  PropertyArea_Semiurban  564 non-null    ui

In [9]:
X.shape

(564, 16)

### Split data into train and test data 

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=0)

In [11]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report, accuracy_score

In [12]:
def print_scores(y_true, y_pred):
    cm = confusion_matrix(y_true,y_pred)
    tn = cm[0,0]
    tp = cm[1,1]
    fp = cm[0,1]
    fn = cm[1,0]
    print(f"Overall Accuracy             : {(tp + tn) / (tp + fp + tn + fn):.2f}")
    print(f"Precision                    : {tp / (tp + fp):.2f}")
    print(f"Recall or TPR or Sensitivity : {tp / (tp + fn):.2f}")
    print(f"Specificity or TNR           : {tn / (tn + fp):.2f}")      

## Logistic Regression

In [13]:
# Importing packages logistic regression and evaluation 
from sklearn.linear_model import LogisticRegression

In [14]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit(X_train)

StandardScaler()

In [15]:
X_train_scaled = ss.transform(X_train)
X_test_scaled = ss.transform(X_test)

In [16]:
# logistic regression   
model = LogisticRegression()
model.fit(X_train_scaled,y_train)

LogisticRegression()

In [17]:
# Check model's performance with train data 
model.score(X_train_scaled,y_train)

0.8248337028824834

In [18]:
y_pred = model.predict(X_test_scaled)

In [19]:
accuracy_score(y_test,y_pred)

0.7787610619469026

In [20]:
confusion_matrix(y_test,y_pred)

array([[13, 22],
       [ 3, 75]], dtype=int64)

In [78]:
print_scores(y_test,y_pred)

Overall Accuracy             : 0.78
Precision                    : 0.77
Recall or TPR or Sensitivity : 0.96
Specificity or TNR           : 0.37


### Display classification report

In [21]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.81      0.37      0.51        35
           1       0.77      0.96      0.86        78

    accuracy                           0.78       113
   macro avg       0.79      0.67      0.68       113
weighted avg       0.79      0.78      0.75       113



In [22]:
y_pred_prob = model.predict_proba(X_test_scaled)

In [27]:
y_pred_prob[:5], y_pred[:5]

(array([[0.24778533, 0.75221467],
        [0.10699829, 0.89300171],
        [0.12604105, 0.87395895],
        [0.12853865, 0.87146135],
        [0.23119301, 0.76880699]]),
 array([1, 1, 1, 1, 1], dtype=int64))

## Decision Tree

In [29]:
from sklearn.tree import DecisionTreeClassifier

In [44]:
model = DecisionTreeClassifier(max_depth=3)
model.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=3)

In [45]:
model.score(X_train,y_train)

0.8403547671840355

In [46]:
y_pred = model.predict(X_test)

In [47]:
confusion_matrix(y_test,y_pred)

array([[15, 20],
       [ 4, 74]], dtype=int64)

In [48]:
print_scores(y_test,y_pred)

Overall Accuracy             : 0.79
Precision                    : 0.79
Recall or TPR or Sensitivity : 0.95
Specificity or TNR           : 0.43


In [49]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.79      0.43      0.56        35
           1       0.79      0.95      0.86        78

    accuracy                           0.79       113
   macro avg       0.79      0.69      0.71       113
weighted avg       0.79      0.79      0.77       113



### Decision Tree Created by Classifier

In [50]:
# Print tree generated by DecisionTreeClassifier
from sklearn.tree import export_text
tree_rules = export_text(model, feature_names=list(X_train))
print(tree_rules)

|--- CreditHistory <= 0.50
|   |--- LoanAmountLog <= 6.30
|   |   |--- LoanAmountLog <= 4.86
|   |   |   |--- class: 0
|   |   |--- LoanAmountLog >  4.86
|   |   |   |--- class: 0
|   |--- LoanAmountLog >  6.30
|   |   |--- class: 1
|--- CreditHistory >  0.50
|   |--- IncomeLog <= 9.90
|   |   |--- IncomeLog <= 7.78
|   |   |   |--- class: 0
|   |   |--- IncomeLog >  7.78
|   |   |   |--- class: 1
|   |--- IncomeLog >  9.90
|   |   |--- IncomeLog <= 10.59
|   |   |   |--- class: 0
|   |   |--- IncomeLog >  10.59
|   |   |   |--- class: 1



### Random Forest

In [90]:
from sklearn.tree import export_text
from sklearn.ensemble import RandomForestClassifier

In [91]:
model = RandomForestClassifier(n_estimators=3, max_depth=3)
model.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=3, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=3,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [92]:
model.score(X_train,y_train)

0.7982261640798226

In [93]:
y_pred = model.predict(X_test)

In [94]:
print_scores(y_test,y_pred)

Overall Accuracy             : 0.75
Precision                    : 0.76
Recall or TPR or Sensitivity : 0.94
Specificity or TNR           : 0.34


In [95]:
# Print internal decision trees
for count, tree in enumerate(model.estimators_):
      # Print tree for each classifier 
      tree_rules = export_text(tree, feature_names =  list(X_train.columns))
      print("Tree : ",count + 1)
      print(tree_rules)      

Tree :  1
|--- Education_Graduate <= 0.50
|   |--- LoanAmountLog <= 5.12
|   |   |--- IncomeLog <= 7.55
|   |   |   |--- class: 0.0
|   |   |--- IncomeLog >  7.55
|   |   |   |--- class: 1.0
|   |--- LoanAmountLog >  5.12
|   |   |--- class: 0.0
|--- Education_Graduate >  0.50
|   |--- CreditHistory <= 0.50
|   |   |--- PropertyArea_Urban <= 0.50
|   |   |   |--- class: 0.0
|   |   |--- PropertyArea_Urban >  0.50
|   |   |   |--- class: 0.0
|   |--- CreditHistory >  0.50
|   |   |--- Dependents <= 1.50
|   |   |   |--- class: 1.0
|   |   |--- Dependents >  1.50
|   |   |   |--- class: 1.0

Tree :  2
|--- Education_Not Graduate <= 0.50
|   |--- CreditHistory <= 0.50
|   |   |--- Gender_Male <= 0.50
|   |   |   |--- class: 0.0
|   |   |--- Gender_Male >  0.50
|   |   |   |--- class: 0.0
|   |--- CreditHistory >  0.50
|   |   |--- IncomeLog <= 7.78
|   |   |   |--- class: 0.0
|   |   |--- IncomeLog >  7.78
|   |   |   |--- class: 1.0
|--- Education_Not Graduate >  0.50
|   |--- SelfEmploy

## KNN 

In [18]:
from sklearn.neighbors import KNeighborsClassifier

In [22]:
model = KNeighborsClassifier(n_neighbors=5)
model.fit(X_train_scaled,y_train)

KNeighborsClassifier()

In [23]:
y_pred = model.predict(X_test_scaled)

In [24]:
print_scores(y_test,y_pred)

Overall Accuracy             : 0.75
Precision                    : 0.76
Recall or TPR or Sensitivity : 0.94
Specificity or TNR           : 0.34


## Naive Bayes 

In [25]:
from sklearn.naive_bayes import GaussianNB

In [26]:
model = GaussianNB()
model.fit(X_train,y_train)

GaussianNB()

In [27]:
model.score(X_train,y_train)

0.8181818181818182

In [28]:
y_pred = model.predict(X_test)

In [29]:
print_scores(y_test,y_pred)

Overall Accuracy             : 0.79
Precision                    : 0.79
Recall or TPR or Sensitivity : 0.95
Specificity or TNR           : 0.43


## Support Vector Machines

In [32]:
from sklearn.svm import SVC

In [34]:
model = SVC()
model.fit(X_train_scaled,y_train)

SVC()

In [36]:
model.score(X_train_scaled,y_train)

0.8337028824833703

In [37]:
y_pred = model.predict(X_test_scaled)

In [38]:
print_scores(y_test,y_pred)

Overall Accuracy             : 0.78
Precision                    : 0.77
Recall or TPR or Sensitivity : 0.96
Specificity or TNR           : 0.37


### GradientBoostingClassifier

In [120]:
from sklearn.ensemble import GradientBoostingClassifier

In [125]:
model = GradientBoostingClassifier()
model.fit(X_train,y_train)

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [126]:
model.score(X_train,y_train)

0.9046563192904656

In [127]:
y_pred = model.predict(X_test)

In [128]:
print_scores(y_test,y_pred)

Overall Accuracy             : 0.79
Precision                    : 0.79
Recall or TPR or Sensitivity : 0.94
Specificity or TNR           : 0.46
